name: movie_mvvm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  shared_preferences: ^2.3.2
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.4.1
  get_it: ^8.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_riverpod: ^2.5.3

flutter:
  uses-material-design: true

  assets:
    - assets/.env
